[theme]
base = "light"
primaryColor = "#16233D"
backgroundColor = "#EEF1F4"
secondaryBackgroundColor = "#E4E8EC"
textColor = "#16233D"
linkColor = "#16233D"
font = "\"Public Sans\""
headingFont = "\"Public Sans\""
baseRadius = "small"
borderColor = "#D8D9D3"

[server]
headless = true
